version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      kubernetes:
        patterns:
          - "k8s.io/api"
          - "k8s.io/apimachinery"
          - "k8s.io/client-go"
          - "k8s.io/apiserver"
          - "k8s.io/code-generator"
          - "k8s.io/component-base"
          - "sigs.k8s.io/controller-runtime"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/attestation/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/bpfvalidator/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/container-build/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/.github/actions/merge-multiarch/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
