fail_fast: false
minimum_pre_commit_version: '0'
repos:
  # more info on the usage: https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
  - repo: https://github.com/golangci/golangci-lint
    rev: 27774aaf853a4fd21f1dd5e69439459dc1b26e68 # v2.13.2
    hooks:
      - id: golangci-lint-full
        language_version: 1.26.5
        stages: [pre-commit]
      - id: golangci-lint-fmt
        language_version: 1.26.5
        stages: [pre-commit]
